version: '3.8'
services:
  db:
    image: postgres:13
    container_name: forum_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=forumdb
    ports:
      - "5432:5432"
    networks:
      - forum_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: forum_app
    build: .
    container_name: forum_app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/forumdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"
    networks:
      - forum_network

networks:
  forum_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

